---
abstract: 'A pluggable Perl web service to preprocess web requests. Plugins can add geo, timezone and browser metadata, and throttle request rate.'
author:
  - 'Clinton Gormley <drtech@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Cerberus
requires:
  Cache::Memcached::Fast: 0
  Carp: 0
  DateTime: 0
  DateTime::TimeZone::Tzfile: 0
  File::Spec::Functions: 0
  FindBin: 0
  Geo::IP: 0
  HTTP::BrowserDetect: 0
  JSON: 0
  List::Util: 0
  Net::IP::Match::Regexp: 0
  Plack::Request: 0
  Plack::Runner: 0
  Pod::Usage: 0
  Time::OlsonTZ::Data: 0
  YAML: 0
  parent: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/clintongormley/App-Cerberus/issues
  repository: git://github.com/clintongormley/App-Cerberus.git
version: 0.07
